#!/usr/bin/env python3
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Copyright (C) 2026 Charles Tobin (CHARL3X)
# Regenerate src/ui/glide_logo.h from the source artwork frames.
#
#   python3 support/gen_logo.py "Glide Logo.png" "Glide Logo Frame 2.png" ...
#
# The boot splash plays these frames as a ping-pong animation. Pipeline: take a
# SINGLE shared crop box (the union of every frame's art bounds) so the wordmark
# never jitters between frames, Lanczos-downscale to fit the 240x135 screen
# (230x115, ~2:1 art), keep it white-on-black, and emit each frame's PNG bytes
# as a const C array. The splash draws them with drawPng over a pure-black
# background, so no color-keying is needed.
import subprocess
import sys
import os
import re

W, H = 200, 100
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src/ui/glide_logo.h")
SRC = os.path.join(ROOT, "support/logo_src")
frames = sys.argv[1:] or [
    os.path.join(SRC, "Glide Logo.png"),
    os.path.join(SRC, "Glide Logo Frame 2.png"),
    os.path.join(SRC, "Glide Logo Frame 3.png"),
    os.path.join(SRC, "Glide Logo Frame 4.png"),
]


def sh(args):
    return subprocess.run(args, check=True, capture_output=True, text=True).stdout


# Union bounding box across all frames (max-stack then trim) -> one crop for all.
box = sh(["magick", *frames, "-evaluate-sequence", "max",
          "-fuzz", "8%", "-format", "%@", "info:"]).strip()
m = re.match(r"(\d+)x(\d+)\+(\d+)\+(\d+)", box)
crop = "%sx%s+%s+%s" % m.groups()
print("shared crop:", crop)

blobs = []
for f in frames:
    tmp = os.path.join(ROOT, "src/ui/_frame.png")
    subprocess.run([
        "magick", f, "-crop", crop, "+repage",
        "-filter", "Lanczos", "-resize", f"{W}x{H}!",
        "-background", "black", tmp,
    ], check=True)
    blobs.append(open(tmp, "rb").read())
    os.remove(tmp)


def carr(name, data):
    rows = "\n".join(
        "    " + ",".join("0x%02x" % b for b in data[i:i + 16]) + ","
        for i in range(0, len(data), 16))
    return f"const uint8_t {name}[] = {{\n{rows}\n}};\n"


arrays = "\n".join(carr(f"kGlideFrame{i}", b) for i, b in enumerate(blobs))
table = "\n".join(
    f"    {{kGlideFrame{i}, sizeof kGlideFrame{i}}}," for i in range(len(blobs)))
total = sum(len(b) for b in blobs)

open(OUT, "w").write(f"""// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Copyright (C) 2026 Charles Tobin (CHARL3X)
// GLIDE wordmark — synthwave animated boot logo. Generated by support/gen_logo.py
// from {len(frames)} source frames: one shared crop box (union of all frames'
// art bounds, so the wordmark never jitters), Lanczos-downscaled to {W}x{H}.
// White line-art on black; the splash plays them ping-pong (0-1-2-3-2-1...) and
// the black background composites seamlessly, so no color-keying is needed.
#pragma once
#include <cstdint>

namespace ui {{

constexpr int kGlideLogoW = {W};
constexpr int kGlideLogoH = {H};

// {len(blobs)} PNG frames, {total} B total. const -> lives in flash, not RAM.
{arrays}
struct LogoFrame {{ const uint8_t* data; uint32_t len; }};
const LogoFrame kGlideFrames[] = {{
{table}
}};
constexpr int kGlideFrameCount = {len(blobs)};

}}  // namespace ui
""")
print(f"wrote {OUT}: {len(blobs)} frames, {total} B PNG total")
